#!/bin/sh /etc/rc.common
# SimAdmin procd init script for OpenWrt (MeiG/314)

USE_PROCD=1
START=99

PROG="/opt/simadmin/simadmin"

start_service() {
    mkdir -p /opt/simadmin
    procd_open_instance
    procd_set_param command "$PROG"
    procd_set_param respawn 3600 5 5
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_set_param env DBUS_SYSTEM_BUS_ADDRESS=unix:path=/var/run/dbus/system_bus_socket
    procd_close_instance
}

reload_service() {
    restart
}
